### ISSUE TITLE
Collect js files from hosts up by gospider - wrong regex

### ISSUE THREAD

**Issue by m4ll0k** [OfJAAH/KingOfBugBountyTips#7]
wrong regex: `... | grep -Eo "(http|https)://[^/\"].*.js+" `  ,  it must be `grep -Eo "(http|https)://[^/\"].*\.js+"`

**Comment by OfJAAH** [comment]
Thanks M4llok !!

**Comment by m4ll0k** [comment]
you can use `egrep` for not extract json file like:

`... | egrep -iv (\.json) | grep -Eo "(http|https)://[^/\"].*\.js+"`

**Comment by OfJAAH** [comment]
;)
